// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKftT9vMyojXyYcZzaZ6783luGsLu1WE',
    appId: '1:442351646330:web:8df476aa002b78e6836dc3',
    messagingSenderId: '442351646330',
    projectId: 'hope-a1e55',
    authDomain: 'hope-a1e55.firebaseapp.com',
    storageBucket: 'hope-a1e55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ztBKc-ZYQaJ_4rDJ33rFrtPkVlo6Yuo',
    appId: '1:442351646330:android:587b3d68d5ef51b7836dc3',
    messagingSenderId: '442351646330',
    projectId: 'hope-a1e55',
    storageBucket: 'hope-a1e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWiZWIa5T2N9Jk04KgF4kxVdSfBPweBA',
    appId: '1:442351646330:ios:2600e3040b8073e3836dc3',
    messagingSenderId: '442351646330',
    projectId: 'hope-a1e55',
    storageBucket: 'hope-a1e55.appspot.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWiZWIa5T2N9Jk04KgF4kxVdSfBPweBA',
    appId: '1:442351646330:ios:2600e3040b8073e3836dc3',
    messagingSenderId: '442351646330',
    projectId: 'hope-a1e55',
    storageBucket: 'hope-a1e55.appspot.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeKftT9vMyojXyYcZzaZ6783luGsLu1WE',
    appId: '1:442351646330:web:dc52cd439e66b946836dc3',
    messagingSenderId: '442351646330',
    projectId: 'hope-a1e55',
    authDomain: 'hope-a1e55.firebaseapp.com',
    storageBucket: 'hope-a1e55.appspot.com',
  );
}
